name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build web app
        run: ./gradlew composeApp:wasmJsBrowserDistribution
      
      - name: List build output
        run: |
          echo "Checking build output directories..."
          echo "=== Directory structure ==="
          ls -la composeApp/build/ || echo "build directory not found"
          echo ""
          echo "=== Looking for JS files ==="
          find composeApp/build -type f -name "*.js" 2>/dev/null | head -20 || echo "No JS files found"
          echo ""
          echo "=== Looking for webpack output ==="
          find composeApp/build -type d -name "*webpack*" 2>/dev/null || echo "No webpack directories"
          echo ""
          echo "=== Full tree (limited depth) ==="
          find composeApp/build -maxdepth 4 -type d 2>/dev/null || echo "Cannot list directories"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Prepare deployment
        run: |
          # Look for the wasmJs build output directory
          BUILD_DIR="composeApp/build/dist/wasmJs/productionExecutable"

          if [ ! -d "$BUILD_DIR" ]; then
            echo "ERROR: WasmJS build output directory not found at $BUILD_DIR"
            echo ""
            echo "Available directories in composeApp/build/dist:"
            ls -la composeApp/build/dist 2>/dev/null || echo "dist directory not found"
            exit 1
          fi

          echo "Found build directory: $BUILD_DIR"
          echo "Contents of build directory:"
          ls -la "$BUILD_DIR"

          # Create deployment directory
          mkdir -p deploy

          # WasmJS build output already includes index.html and all necessary files
          # Just copy everything from the build directory
          echo "Copying all build output files..."
          cp -r "$BUILD_DIR"/* deploy/

          # Copy vercel.json
          cp vercel.json deploy/

          echo "Files copied to deploy directory:"
          ls -la deploy/

          echo "Deployment directory contents:"
          ls -la deploy/

          # Verify index.html exists
          if [ ! -f "deploy/index.html" ]; then
            echo "ERROR: index.html not found in deploy directory!"
            echo "Files in deploy directory:"
            find deploy -type f
            exit 1
          fi

          echo "✓ index.html found in deployment directory"

          echo ""
          echo "All JavaScript files in deploy directory:"
          find deploy -name "*.js" -type f | sort

          echo ""
          echo "Verifying all required dependencies are present..."
          if find deploy -name "kotlin-kotlin-stdlib*.js" -type f | grep -q .; then
            echo "✓ kotlin-stdlib found"
          else
            echo "⚠ WARNING: kotlin-stdlib not found!"
          fi

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          cd deploy
          vercel deploy --prod --yes --token=$VERCEL_TOKEN
